create table if not exists public.select_options (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  select_identifier text not null,
  value text not null,
  color text not null default '#71717a',
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint select_options_color_hex check (color ~ '^#[0-9A-Fa-f]{6}$'),
  constraint select_options_user_value_unique unique (user_id, select_identifier, value)
);

create index if not exists select_options_user_select_position_idx
  on public.select_options (user_id, select_identifier, position, id);

alter table public.select_options enable row level security;

create policy "Users can read their select options"
  on public.select_options
  for select
  using (auth.uid() = user_id);

create policy "Users can create their select options"
  on public.select_options
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their select options"
  on public.select_options
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their select options"
  on public.select_options
  for delete
  using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_select_options_updated_at on public.select_options;

create trigger set_select_options_updated_at
  before update on public.select_options
  for each row
  execute function public.set_updated_at();
