import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/menu";
import { Footer } from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      data-theme="silk"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} bg-base-100 h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <div className="flex flex-1">
          <Menu />
          <main className="bg-base-200 border-base-300 mx-4 my-2 flex-1 rounded border p-4 shadow">{children}</main>
        </div>

        <Footer />
      </body>
    </html>
  );
}
